version: 0.0
os: linux
files:
  - source: /
    destination: /home/linme/front/linme-client-web/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/build_react_app
      timeout: 300
      runas: linme
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

