version: 0.0
os: linux
files:
  - source: /
    destination: /home/linme/front/linme-client-web/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: linme
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: linme
