version: 0.0
os: linux
files:
  - source: /
    destination: /home/linme/front/linme-client-web/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 1200
      runas: linme
  ApplicationStart:
    - location: scripts/start_server
      timeout: 600
      runas: linme
