#!/bin/bash
source ~/.bashrc

echo "NVM 설치 확인 및 설치"
if [ ! -d "$HOME/.nvm" ]; then
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
fi

echo "Node.js 버전 설정"
nvm install v20.9.0
nvm use v20.9.0

echo "yarn과 pm2 설치 확인"
# yarn 설치 확인 및 설치
if ! command -v yarn &> /dev/null; then
    echo "yarn이 설치되지 않았습니다. 설치 중..."
    npm install -g yarn
else
    echo "yarn이 이미 설치되어 있습니다."
fi

echo "pm2 설치 확인 및 설치"
if ! command -v pm2 &> /dev/null; then
    echo "pm2가 설치되지 않았습니다. 설치 중..."
    yarn global add pm2  # sudo 없이 pm2를 로컬로 설치
    export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
else
    echo "pm2가 이미 설치되어 있습니다."
fi

echo "애플리케이션 디렉토리로 이동"
cd /home/linme/front/linme-client-web || exit

# pm2 프로세스 삭제 (필요한 경우)
pm2 delete linme-client-web

# 캐시 정리
yarn cache clean

# 의존성 설치
yarn install

# 빌드
yarn build-dev

# 애플리케이션 시작
pm2 start "yarn start-dev" --name linme-client-web
