#!/bin/bash
export NVM_DIR=$HOME/.nvm;
source $NVM_DIR/nvm.sh;

nvm use v20.9.0
echo 'Installing dependencies...'

# 작업 디렉터리를 프로젝트 경로로 변경
cd /home/linme/front/linme-client-web

# 권한 문제 방지
sudo chown -R linme:linme /home/linme/front/linme-client-web

yarn cache clean
yarn install --network-timeout 600000

echo 'Running build...'
yarn build-dev
